# Generated by Django 4.2.3 on 2023-07-10 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Descriptors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val1', models.FloatField(max_length=30)),
                ('val2', models.FloatField(max_length=30)),
                ('val3', models.FloatField(max_length=30)),
                ('val4', models.FloatField(max_length=30)),
                ('val5', models.FloatField(max_length=30)),
                ('val6', models.FloatField(max_length=30)),
                ('val7', models.FloatField(max_length=30)),
                ('val8', models.FloatField(max_length=30)),
                ('val9', models.FloatField(max_length=30)),
                ('val10', models.FloatField(max_length=30)),
            ],
        ),
    ]
